# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/mem_music.xci
# IP: The module: 'mem_music' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/mem_music_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_music'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/mem_music.xci
# IP: The module: 'mem_music' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/mem_music_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_music'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
