# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/digital logic/piano/piano.cache/wt} [current_project]
set_property parent.project_path {D:/digital logic/piano/piano.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/digital logic/piano/piano.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/digital logic/piano/piano.srcs/sources_1/ip/mem_lib/music_library.coe}}
add_files {{D:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/musc_sheet.coe}}
add_files {{D:/digital logic/piano/piano.srcs/sources_1/ip/keyboard_set.coe}}
read_verilog -library xil_defaultlib {
  {D:/digital logic/piano/piano.srcs/sources_1/new/CONSTANT.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/BPM_Counter.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/Button_Debouncer.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/Buzzer.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/State_FSM.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/keyboard.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/led_ctrl.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/music_lib.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/note_MUX.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/note_swift.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/seg_light_7.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/tub_7_library.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/vga_character.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/vga_ctrl.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/vga_display_char.v}
  {D:/digital logic/piano/piano.srcs/sources_1/new/TOP.v}
}
read_ip -quiet {{D:/digital logic/piano/piano.srcs/sources_1/ip/mem_lib/mem_lib.xci}}
set_property used_in_implementation false [get_files -all {{d:/digital logic/piano/piano.srcs/sources_1/ip/mem_lib/mem_lib_ooc.xdc}}]

read_ip -quiet {{D:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/mem_music.xci}}
set_property used_in_implementation false [get_files -all {{d:/digital logic/piano/piano.srcs/sources_1/ip/mem_music/mem_music_ooc.xdc}}]

read_ip -quiet {{d:/digital logic/piano/piano.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/digital logic/piano/piano.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/digital logic/piano/piano.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/digital logic/piano/piano.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/digital logic/piano/piano.srcs/constrs_1/constrains.xdc}}
set_property used_in_implementation false [get_files {{D:/digital logic/piano/piano.srcs/constrs_1/constrains.xdc}}]


synth_design -top TOP -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
