set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN R1 [get_ports enable]
set_property PACKAGE_PIN N4 [get_ports rst]
set_property PACKAGE_PIN H17 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
