set_property PACKAGE_PIN P5 [get_ports {operation[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operation[0]}]
set_property PACKAGE_PIN P4 [get_ports {operation[6]}]
set_property PACKAGE_PIN P3 [get_ports {operation[5]}]
set_property PACKAGE_PIN P2 [get_ports {operation[4]}]
set_property PACKAGE_PIN R2 [get_ports {operation[3]}]
set_property PACKAGE_PIN M4 [get_ports {operation[2]}]
set_property PACKAGE_PIN N4 [get_ports {operation[1]}]
set_property PACKAGE_PIN R1 [get_ports {operation[0]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property PACKAGE_PIN H17 [get_ports speaker]
