webtalk_init -webtalk_dir C:/Users/Langchu HUANG/OneDrive - SUSTech/Desktop/piano/piano.sim/sim_1/behav/xsim/xsim.dir/tbc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan  2 15:57:25 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "21fd8c79-ce10-4b54-a49b-6ecbb4a76512" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c1f4db5da62b455a8d499357099c6af8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "509" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "14148675100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17784_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3665378535 -regid "" -xml C:/Users/Langchu HUANG/OneDrive - SUSTech/Desktop/piano/piano.sim/sim_1/behav/xsim/xsim.dir/tbc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Langchu HUANG/OneDrive - SUSTech/Desktop/piano/piano.sim/sim_1/behav/xsim/xsim.dir/tbc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Langchu HUANG/OneDrive - SUSTech/Desktop/piano/piano.sim/sim_1/behav/xsim/xsim.dir/tbc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
